CREATE TABLE user_profile
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             VARCHAR NOT NULL,
    bio                 TEXT,
    hobbies             TEXT[]  NOT NULL,
    political_views     VARCHAR,
    relationship_status VARCHAR
);
