spring:
    data:
        mongodb:
            database: feed
            uri: mongodb://localhost:27017/feed?authSource=admin
            username: ${MONGODB_USERNAME}
            password: ${MONGODB_PASSWORD}
    application:
        name: feed-service

server:
    port: 8081

