spring:
  data:
    mongodb:
      database: feed
      uri: mongodb://localhost:27017/feed?authSource=admin&retryWrites=false
      replica-set-name: rs0
  application:
    name: feed-service

  config:
    import: application-kafka.yml

gateway.url: http://localhost:8765

server:
  port: 8081

