spring:
    data:
        mongodb:
            database: feed
            uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017/feed?authSource=admin
    application:
        name: feed-service

    config:
      import: optional:configserver:http://localhost:8888/config-server

server:
    port: 8081

