spring:
    data:
        mongodb:
            database: feed
            uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017/feed
    application:
        name: feed-service

server:
    port: 8081

