spring:
  data:
    mongodb:
      database: feed
      uri: mongodb://${FEED_DB_HOST:localhost}:27017/feed?authSource=admin&retryWrites=false
      replica-set-name: rs0
  application:
    name: feed-service

  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost:8888}/config-server
  profiles:
    active: kafka
server:
  port: ${FEED_SERVICE_PORT}

