apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
data:
  KAFKA_ENABLE_KRAFT: "true"
  KAFKA_CFG_NODE_ID: "0"
  KAFKA_CFG_BROKER_ID: "0"
  KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-0.kafka-service:9093,1@kafka-1.kafka-service:9093,2@kafka-2.kafka-service:9093"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://${KAFKA_HOST}:9092"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  ALLOW_PLAINTEXT_LISTENER: "true"
  KAFKA_KRAFT_CLUSTER_ID: "r4zt_wrqTRuT7W2NJsB_GA"
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
