spring:
  application.name: authentication-service
  datasource:
    url: jdbc:postgresql://${KEYCLOAK_HOST}:5432/keycloak
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security.oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/certs
    client:
      provider:
        keycloak:
          issuer-uri: http://${KEYCLOAK_HOST}:8080/realms/ano-hub
      registration:
        keycloak-client:
          provider: keycloak
          client-id: keycloak-client
          client-secret: ${CLIENT_SECRET}
          authorization-grant-type: authorization_code
          scope: openid
          redirect-uri: http://${KEYCLOAK_HOST}:${server.port}/login/oauth2/code/keycloak-client

keycloak:
  server-url: http://${KEYCLOAK_HOST}:8080
  realm: ano-hub

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
