spring:
  config:
    import: configserver:http://${DISCOVERY_SERVER_HOST:localhost}:8888/config-server
  profiles:
    active: kafka
  application.name: authentication-service
  datasource:
    url: jdbc:postgresql://${KEYCLOAK_HOST:localhost}:5433/keycloak
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security.oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/certs
    client:
      provider:
        keycloak:
          issuer-uri: ${keycloak.server-url}/realms/ano-hub
      registration:
        keycloak-client:
          provider: keycloak
          client-id: keycloak-client
          client-secret: ${CLIENT_SECRET}
          authorization-grant-type: authorization_code
          scope: openid
          redirect-uri: http://${keycloak.host}:${server.port}/login/oauth2/code/keycloak-client

keycloak:
  host: ${KEYCLOAK_HOST:localhost}
  port: ${KEYCLOAK_PORT:9080}
  server-url: http://${keycloak.host}:${keycloak.port}
  realm: ano-hub
jwt:
  auth:
    converter:
      resource-id: keycloak-client
      principle-attribute: preferred_username

server:
  port: 8085

