spring:
  data:
    mongodb:
      database: private_chats
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${PRIVATE_CHATS_DB_HOST:localhost}:27018/private_chats?authSource=admin
  application:
    name: private-chats-service

  config:
    import: application-kafka.yml

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}

server:
  port: ${PRIVATE_CHAT_PORT:8084}