spring:
  data:
    mongodb:
      database: private_chats
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@27018/private_chats?authSource=admin
  application:
    name: private-chats-service

  config:
    import: application-kafka.yml

server:
  port: 8084