spring:
  data:
    mongodb:
      database: private_chats
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${PRIVATE_CHATS_DB_HOST}:27018/private_chats?authSource=admin
  application:
    name: private-chats-service

  config:
    import: optional:configserver:http://config-server:8888/config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 8084