spring:
  data:
    mongodb:
      database: private_chats
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${PRIVATE_CHATS_DB_HOST}:${PRIVATE_CHAT_DB_PORT}/private_chats?authSource=admin
  application:
    name: private-chats-service

  config:
    import: application-kafka.yml

server:
  port: ${PRIVATE_CHAT_PORT}