spring:
  data:
    mongodb:
      database: private_chats
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${PRIVATE_CHATS_DB_HOST:localhost}:27018/private_chats?authSource=admin
  application:
    name: private-chats-service

  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost:8888}/config-server

server:
  port: 8084