apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  CONFIG_SERVER_URL: "config-server.example.com:8888"
  DISCOVERY_SERVER_URL: "discovery-server:80"
  PRIVATE_CHATS_DB_HOST: "private-chats-db"
  USER_PROFILES_DB_HOST: "user-profiles-db"
  FRIENDS_DB_HOST: "friends-db"
  FEED_DB_HOST: "feed-db"
  KAFKA_HOST1: "localhost"
  KAFKA_HOST2: "localhost"
  KAFKA_HOST3: "localhost"
  GATEWAY_HOST: "gateway"
  KEYCLOAK_HOST: "keycloak-db"
  KEYCLOAK_PORT: "8080"
  CASSANDRA_CLUSTER_NAME: "abo_hub"
