spring:
  application.name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_model_service
          uri: lb://user-model-service/api/**
          predicates:
            - Path=/user-model-app/**
        - id: feed_service
          uri: lb://feed-service
          predicates:
            - Path=/feed-app/api/**

  config:
    import: optional:configserver:http://config-server:8888/config-server

server:
  port: 8765