spring:
  application.name: user-profile-service
  config:
    import: application-kafka.yml
  cassandra:
    contact-points: ${USER_PROFILES_DB_HOST}:${USER_PROFILES_DB_PORT}
    keyspace-name: user_profiles
    local-datacenter: datacenter1
    username: ${USER_PROFILES_DB_USER}
    password: ${USER_PROFILES_DB_PASSWORD}

logging:
  level:
    org.apache.kafka.clients:
      NetworkClient: ERROR
      consumer.internals.ConsumerCoordinator: ERROR

server:
  port: ${USER_PROFILE_PORT}
