spring:
  config:
    import: application-kafka.yml
  cassandra:
    contact-points: ${USER_PROFILES_DB_HOST:127.0.0.1}:9042
    keyspace-name: user_profiles
    local-datacenter: datacenter1
    username: ${CASSANDRA_USER}
    password: ${CASSANDRA_PASSWORD}

logging:
  level:
    org.apache.kafka.clients:
      NetworkClient: ERROR
      consumer.internals.ConsumerCoordinator: ERROR

server:
  port: 8087
