spring:
  application.name: user-profile-service
  config:
    import: configserver:http://${DISCOVERY_SERVER_HOST:localhost}:8888/config-server
  profiles:
    active: kafka
  cassandra:
    keyspace-name: user_profiles
    local-datacenter: dc1
    contact-points: ${USER_PROFILES_DB_HOST:localhost}:9042
    username: ${CASSANDRA_USER}
    password: ${CASSANDRA_PASSWORD}

server:
  port: 8087
