spring:
  application.name: user-profile-service
  config:
    import: application-kafka.yml
  cassandra:
    contact-points: ${USER_PROFILES_DB_HOST:127.0.0.1}:9042
    keyspace-name: user_profiles
    local-datacenter: datacenter1
    username: ${USER_PROFILES_DB_USER}
    password: ${USER_PROFILES_DB_PASSWORD}

logging:
  level:
    org.apache.kafka.clients:
      NetworkClient: ERROR
      consumer.internals.ConsumerCoordinator: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}

server:
  port: ${USER_PROFILE_PORT:8087}
