spring:
  application.name: user-profile-service
  config:
    import: configserver:http://${DISCOVERY_SERVER_HOST:localhost}:8888/config-server
  profiles:
    active: kafka
  cassandra:
    keyspace-name: user_profiles
    local-datacenter: datacenter1
    username: ${CASSANDRA_USER}
    password: ${CASSANDRA_PASSWORD}

logging:
  level:
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: ERROR

server:
  port: 8087
