spring:
  application.name: user-profile-service
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5434/user_profiles
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5434/user_profiles
    driver-class-name: org.postgresql.Driver

  config:
    import: optional:configserver:http://localhost:8888/config-server

  # Kafka Consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: saga-user-group-id
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: '*'

    #Kafka Producer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      auto-create: true

kafka:
  topics:
    user-profile-deleted: user-profile-deleted-topic
    failed-event: failed-event-topic

server:
  port: 8083
