version: '3.7'

services:
  friends_db:
    container_name: friends_db
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: friends
    ports:
      - "5432:5432"
    volumes:
      - friends_data:/var/lib/postgresql/data
    networks:
      - backend

  feed_db:
    container_name: feed_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: feed
    ports:
      - "27017:27017"
    volumes:
      - feed_data:/data/db
    networks:
      - backend

  private_chats_db:
    container_name: private_chats_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: private_chats
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - "27018:27017"
    volumes:
      - private_chats:/data/db
    networks:
      - backend

  user_profiles_db:
    container_name: user_profiles_db
    image: cassandra:5.0
    environment:
      CASSANDRA_CLUSTER_NAME: abo_hub
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
      CASSANDRA_DC: datacenter1
    ports:
      - "9042:9042"
    volumes:
      - user_profiles_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'describe cluster'" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:5.0
    environment:
      CASSANDRA_CLUSTER_NAME: abo_hub
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
    depends_on:
      user_profiles_db:
        condition: service_healthy
    volumes:
      - ../db/cassandra/init.cql:/init.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh user_profiles_db -f /init.cql"
    networks:
      - backend

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    depends_on:
      - redis_insight
    ports:
      - "6379:6379"

  redis_insight:
    image: redislabs/redisinsight:1.9.0
    container_name: redis_insight
    restart: always
    ports:
      - "8001:8001"

networks:
  backend:
    name: backend
    external: true

volumes:
  feed_data:
  friends_data:
  private_chats:
  user_profiles_data:


