version: '3.7'

services:
  keycloak_db:
    image: postgres:16.1
    container_name: keycloak_db
    environment:
      POSTGRES_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - keycloak_db_data:/bitnami/postgresql
    ports:
      - "5433:5432"
    networks:
      - keycloak

  keycloak:
    image: bitnami/keycloak:24.0.2
    user: root
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: keycloak_db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_USER: ${POSTGRES_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_EXTRA_ARGS: --import-realm
      KEYCLOAK_CREATE_ADMIN_USER: true
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    volumes:
      - ../keycloak/theme:/opt/bitnami/keycloak/themes/
      - ../keycloak/realms/:/opt/bitnami/keycloak/data/import
    #    command: /opt/bitnami/keycloak/bin/kc.sh start-dev --import-realm
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge

volumes:
  keycloak_db_data: