version: '3.7'

services:
  keycloak_db:
    image: postgres:16.1
    container_name: ${KEYCLOAK_DB_HOST}
    environment:
      POSTGRES_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_db_data:/bitnami/postgresql
    ports:
      - ${KEYCLOAK_DB_PORT_EXP}:${KEYCLOAK_DB_PORT}
    networks:
      - keycloak

  keycloak:
    image: bitnami/keycloak:24.0.2
    user: root
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: ${KEYCLOAK_DB_HOST}
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DB_NAME}
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DB_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_EXTRA_ARGS: --import-realm
      KEYCLOAK_CREATE_ADMIN_USER: "true"
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    depends_on:
      - keycloak_db
    volumes:
      - ../keycloak/theme:/opt/bitnami/keycloak/themes/
      - ../keycloak/realms/:/opt/bitnami/keycloak/data/import
    #    command: /opt/bitnami/keycloak/bin/kc.sh start-dev --import-realm
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge

volumes:
  keycloak_db_data: