spring:
  r2dbc:
    url: r2dbc:postgresql://${FRIENDS_DB_HOST:localhost}:5432/friends
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  application.name: friends-service

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${FRIENDS_DB_HOST:localhost}:5432/friends
    driver-class-name: org.postgresql.Driver

  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost:8888}/config-server
  profiles:
    active: ${ACTIVE PROFILE}

server:
  port: ${FRIENDS_SERVICE_PORT}
