spring:
  application.name: discovery-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:8761/eureka/
  instance:
    hostname: discovery-server

server:
  port: 8761
