spring:
  data:
    mongodb:
      uri: mongodb://${NOTIFICATION_DB_HOST:localhost}:27019/notification?authSource=admin
  profiles:
    active: ${ACTIVE_PROFILE:kafka}
  application.name: notification-service

server:
  port: ${NOTIFICATION_SERVICE_PORT:8086}