spring:
  data:
    mongodb:
      uri: mongodb://${NOTIFICATION_DB_HOST:localhost}:27019/notification?authSource=admin
  config:
    import: application-kafka.yml
  application.name: notification-service

server:
  port: 8086