apiVersion: v1
kind: Service
metadata:
  name: feed-service
spec:
  selector:
    app: feed-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
spec:
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service
          image: kamomillte/feed-service
          imagePullPolicy: Always
          resources:
            limits:
              memory: 500M
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: s3cr3ts
            - secretRef:
                name: db-secrets
            - configMapRef:
                name: common-config
