version: '3.7'

services:
  config-server:
    container_name: config-server
    env_file:
      - .env
    image: kamomillte/config-server
    depends_on:
      - discovery-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  discovery-server:
    container_name: discovery-server
    env_file:
      - .env
    image: kamomillte/discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  gateway:
    container_name: gateway
    env_file:
      - .env
    image: kamomillte/gateway
    depends_on:
      - discovery-server
    ports:
      - "8765:8765"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  feed-service:
    container_name: feed-service
    env_file:
      - .env
    image: kamomillte/feed-service
    ports:
      - "8081:8081"
    depends_on:
      - feed_db
      - user-model-service
      - gateway
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  private-chat-service:
    container_name: private-chat-service
    env_file:
      - .env
    image: kamomillte/private-chat-service
    ports:
      - "8084:8084"
    depends_on:
      - private_chats_db
      - gateway
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  user-model-service:
    container_name: user-model-service
    env_file:
      - .env
    image: kamomillte/user-model-service
    ports:
      - "8083:8083"
    depends_on:
      - users_db
      - gateway
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

networks:
  backend:
    driver: bridge
