version: '3.7'

services:
  friends_db:
    container_name: friends_db
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: friends
    ports:
      - "5432:5432"
    volumes:
      - friends_data:/var/lib/postgresql/data
    networks:
      - backend

  feed_db:
    container_name: feed_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: feed
    ports:
      - "27017:27017"
    volumes:
      - feed_data:/data/db
    networks:
      - backend

  private_chats_db:
    container_name: private_chats_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: private_chats
    ports:
      - "27018:27017"
    volumes:
      - private_chats:/data/db
    networks:
      - backend

  keycloak-db:
    image: postgres:16.1
    environment:
      POSTGRES_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - keycloak_data:/data/db

  keycloak:
    image: bitnami/keycloak
    user: root
    environment:
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: keycloak-db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_USER: ${POSTGRES_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "9080:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak_data:/opt/jboss/keycloak/standalone/data/
    networks:
      - backend

  user_profiles_db:
    container_name: user_profiles_db
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user_profiles
    ports:
      - "5434:5432"
    volumes:
      - user_profiles_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    name: backend
    external: true

volumes:
  feed_data:
  friends_data:
  private_chats:
  keycloak_data:
  keycloak_db_data:
  user_profiles_data: