version: '3.7'

services:
  users_db:
    container_name: users_db
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

  feed_db:
    container_name: feed_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: feed
    ports:
      - "27017:27017"
    volumes:
      - feed_data:/data/db

  private_chats_db:
    container_name: private_chats_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: private_chats
    ports:
      - "27018:27017"
    volumes:
      - private_chats:/data/db

  config-server:
    container_name: config-server
    env_file:
      - .env
    image: kamomillte/config-server
    ports:
      - "8888:8888"

  discovery-server:
    container_name: discovery-server
    env_file:
      - .env
    image: kamomillte/discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    container_name: gateway
    env_file:
      - .env
    image: kamomillte/gateway
    depends_on:
      - discovery-server
    ports:
      - "8765:8765"

  feed-service:
    container_name: feed-service
    env_file:
      - .env
    image: kamomillte/feed-service
    ports:
      - "8081:8081"
    depends_on:
      - feed_db
      - gateway
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  private-chat-service:
    container_name: private-chat-service
    env_file:
      - .env
    image: kamomillte/private-chat-service
    ports:
      - "8081:8081"
    depends_on:
      - private_chats_db
      - gateway
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-model-service:
    container_name: user-model-service
    env_file:
      - .env
    image: kamomillte/user-model-service
    ports:
      - "8083:8083"
    depends_on:
      - users_db
      - gateway
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  feed_data:
  users_data:
  private_chats: