version: '3.7'

services:
  friends_db:
    container_name: friends_db
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: friends
    ports:
      - "5432:5432"
    volumes:
      - friends_data:/var/lib/postgresql/data
    networks:
      - backend

  feed_db:
    container_name: feed_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: feed
    ports:
      - "27017:27017"
    volumes:
      - feed_data:/data/db
    networks:
      - backend

  private_chats_db:
    container_name: private_chats_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: private_chats
    ports:
      - "27018:27017"
    volumes:
      - private_chats:/data/db
    networks:
      - backend

  keycloak-db:
    image: postgres:16.1
    container_name: keycloak_db
    environment:
      POSTGRES_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - backend

  keycloak:
    image: bitnami/keycloak
    user: root
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: keycloak-db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_USER: ${POSTGRES_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "9080:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak/theme:/opt/bitnami/keycloak/themes/
      - ./keycloak/keycloak_data:/opt/bitnami/keycloak/data/import
    command: /opt/bitnami/keycloak/bin/kc.sh start-dev --import-realm
    networks:
      - backend

  user_profiles_db:
    container_name: user_profiles_db
    image: cassandra:latest
    command: >
      bash -c 'if [[ "$$CASSANDRA_USER" && "$$CASSANDRA_PASSWORD" ]]; then 
      /usr/local/bin/docker-entrypoint.sh; 
      fi && 
      until echo "describe cluster;" | cqlsh -u $$CASSANDRA_USER -p $$CASSANDRA_PASSWORD; do 
      echo "Waiting for Cassandra..."; 
      sleep 5; 
      done && 
      cqlsh -u $$CASSANDRA_USER -p $$CASSANDRA_PASSWORD -f /init.cql'
    environment:
      CASSANDRA_CLUSTER_NAME: abo_hub
      CASSANDRA_DC: dc1
      #      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
    ports:
      - "9042:9042"
    volumes:
      - user_profiles_data:/var/lib/cassandra
      - ./db/cassandra/init.cql:/init.cql
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'describe cluster'" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend


  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "CASSANDRA_CLUSTER_NAME=abo_hub"
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - user_profiles_data:/var/lib/cassandra

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    environment:
      - "CASSANDRA_CLUSTER_NAME=abo_hub"
    depends_on:
      - cassandra
    volumes:
      - ./db/cassandra/init.cql:/init.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /init.cql"

  kafka:
    image: 'bitnami/kafka:3.4.1'
    container_name: kafka
    environment:
      KAFKA_ENABLE_KRAFT: true
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_BROKER_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST}:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: true
      KAFKA_KRAFT_CLUSTER_ID: r4zt_wrqTRuT7W2NJsB_GA
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - backend

networks:
  backend:
    name: backend
    external: true

volumes:
  feed_data:
  friends_data:
  private_chats:
  keycloak_data:
  keycloak_db_data:
  user_profiles_data:


