spring:
  application.name: config-server
  cloud.config.server.prefix: /config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:LeraPkl/AnoHub.git
          clone-on-start: true
          timeout: 10
          skip-ssl-validation: true
          private-key: ${GITHUB_PRIVATE_KEY}

server.port: 8888
eureka:
  client:
    enabled: false
