spring:
  application.name: config-server
  cloud.config.server.prefix: /config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:LeraPkl/AnoHub.git
          clone-on-start: true
          delete-untracked-branches: true
          ignore-local-ssh-settings: true
          refresh-rate: 300
          private-key: ${GIT_PRIVATE_KEY}
    vault:
      token: 00000000-0000-0000-0000-000000000000
      scheme: http
      authentication: TOKEN
      host: 127.0.0.1
      port: 8200
      kv.enabled: true
      application-name: config-server
  config:
    import: classpath:/env.yml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server.port: 8888