spring:
  application.name: config-server
  cloud.config.server.prefix: /config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeraPkl/config-server.git
          username: LeraPkl
          password: ${GITHUB_PAT}
          clone-on-start: true
          timeout: 10
          skip-ssl-validation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_URI:localhost:8761}/eureka/

server.port: ${CONFIG_SERVER_PORT:8888}
