spring:
  application.name: config-server
  cloud.config.server.prefix: /config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeraPkl/AnoHub.git
          username: LeraPkl
          password: ${GITHUB_PAT}
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

gateway.url: http;//discovery-server:8765
