apiVersion: v1
kind: Service
metadata:
  name: keycloak-db-service
spec:
  selector:
    app: keycloak-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-db
spec:
  serviceName: keycloak-db
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: postgres:16.1
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: keycloak-data
              mountPath: /data/db
          env:
            - name: POSTGRES_DB
              value: keycloak
          envFrom:
            - secretRef:
                name: db-secrets
            - configMapRef:
                name: common-config
  volumeClaimTemplates:
    - metadata:
        name: keycloak-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
