apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: keycloak-realm
          configMap:
            name: keycloak-chart-cm
      containers:
        - name: keycloak
          image: bitnami/keycloak:24.0.2
          volumeMounts:
            - name: keycloak-realm
              mountPath: /opt/bitnami/keycloak/data/import
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: db-secrets
          - configMapRef:
              name: common-config
          - configMapRef:
              name: keycloak-cm
          env:
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: KEYCLOAK_USER
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: KEYCLOAK_PASSWORD
            - name: KEYCLOAK_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
