name: Java CI with Gradle

on:
  push:
    branches: [ "main" , "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        env:
          GIT_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
        run: ./gradlew bootBuildImage

      - name: Push Docker images
        run: |
          for dir in $(find . -type d -name "src" -exec dirname {} \;); do
          if grep -q 'bootBuildImage\s*{\s*enabled\s*=\s*true' "$dir/build.gradle"; then
          service_name=$(basename "$dir")
          docker tag $service_name:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/$service_name:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/$service_name:${{ github.run_number }}
          fi
          done